#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail


SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$SCRIPT_DIR/launcher"

# shellcheck source=launcher/ui.sh
source "$SRC_DIR/ui.sh"
# shellcheck source=launcher/env.sh
source "$SRC_DIR/env.sh"
# shellcheck source=launcher/git.sh
source "$SRC_DIR/git.sh"
# shellcheck source=launcher/find_terminal.sh
source "$SRC_DIR/find_terminal.sh"
# shellcheck source=launcher/de.sh
source "$SRC_DIR/de.sh"


# =============================
# Основная логика
# =============================
# Обрабатывает полученные при запуске аргументы:
#   - устанавливает переменные окружения в зависимости от опций
#   - при запросе на вывод подсказки или версии завершает работу после вывода
# -----------------------------
# Выводит приветственное сообщение с названием и версией
# -----------------------------
# Устанавливает переменные окружения и настраивает основную логику работы:
#   - форматирование вывода в зависимости от выбранного режима работы
#   - поведение режима отладки, если он активирован
# -----------------------------
# Обновляет сабмодуль
# -----------------------------
# Запускает целевой скрипт из сабмодуля
#
# Если скрипт не был запущен интерактивно или был активирован режим отладки:
#   - произведёт поиск терминала по умолчанию:
#     - если DE поддерживается, то возьмёт терминал из его настроек
#     - иначе — возьмёт первый попавшийся из подготовленного списка
#   - (debug) при получении запрета на запуск в новом окне пропустит этап поиска
#     и запустит целевой скрипт в интерактивном режиме в текущем терминале
# =============================

parse_args "$@"

init_format
show_hello

# =============================
# Инициализирует важные переменные:
# -----------------------------
# - REPO_TOOLS_PATH
# - REPO_ROOT
# =============================
init_env

update_submodule "$REPO_TOOLS_PATH" "$REPO_ROOT" "$TARGET_BRANCH"

if [[ -v DEBUG && $DEBUG_FORCE_WINDOW -eq 1 ]]; then
  e_debug "$(f_bold "Запуск в режиме отладки") (открытие нового окна принудительно)"
  run_in_terminal "$TARGET_SCRIPT"
  exit 0
fi

if test -t 0; then
  e_info "Запуск интерактивного меню..."
  $TARGET_SCRIPT
  exit 0
fi

run_in_terminal "$TARGET_SCRIPT"
